### ISSUE TITLE
Diff not showing correctly on Array shift operations.

### ISSUE THREAD

**Issue by hemandev** [cosmicanant/recursive-diff#18]
Consider the objects below
```js
var initialVal = [
  {
    name: "Sam",
    title: "Marketing manager",
    email: "sam@gg.com"
  },
  { 
    name: "Abel", 
    title: "Director", 
    email: "abel@ff.com"
   }
];
var changedVal = [
  { name: "Abel Smith", title: "Director", email: "abel@ff.com" }
];

console.log(getDiff(initialVal, changedVal));
```
This is the output I get
```js
0: Object
op: "update"
path: Array(2)
val: "Abel Smith"
oldVal: "Sam"
1: Object
op: "update"
path: Array(2)
val: "Director"
oldVal: "Marketing manager"
2: Object
op: "update"
path: Array(2)
val: "abel@ff.com"
oldVal: "sam@gg.com"
3: Object
op: "delete"
path: Array(1)
0: 1
oldVal: Object
name: "Abel"
title: "Director"
email: "abel@ff.com"
```
The object that got deleted is 
```js
 {
    name: "Sam",
    title: "Marketing manager",
    email: "sam@gg.com"
  },
  ```
  But it's not being captured.
  This happens because we are preserving the array order.
  Can we add an additional flag which when set to true checks whether the element was in the array or not regardless of the order?

**Comment by cosmicanant** [comment]
@hemanditwiz yeah, the diff algorithm is based on comparing elements in their preserved order. Also, I think the feature you are asking, is not something that is commonly used, so I would avoid adding this feature to the library. Feel free to fork this repo and implement the additional functionality.
