### ISSUE TITLE
please remove rouge version from npm

### ISSUE THREAD

**Issue by dbuezas** [cosmicanant/recursive-diff#3]
recursive-diff.js is broken, recursive-diff is right

**Comment by cosmicanant** [comment]
I have no idea why rogue version of  recursive-diff has been published even if there was [recursive-diff](https://www.npmjs.com/package/recursive-diff) . As you might observe, someone has forked recursive-diff repo and published it with another similar name [recursive-diff.js](https://www.npmjs.com/package/recursive-diff.js)

**Comment by cosmicanant** [comment]
Recursive-diff.js is deleted after a support request raised for removing duplicate package from npmjs registry. Thanks to npmjs support team.

**Comment by cosmicanant** [comment]
Seems fixed now.
