### ISSUE TITLE
I want to have this to TypeScript revision for Angular 2 .. do u have that support ?? 

### ISSUE THREAD

**Issue by sameh-g** [cosmicanant/recursive-diff#6]

**Comment by cosmicanant** [comment]
@sameh-g Sure, will add support for typescript. If you like, you can also contribute.

**Comment by mmakrzem** [comment]
Still no typescript definition file for this project?  I too would like to use this project in my Typescript application. https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by cosmicanant** [comment]
ok, typescript support has been added with the latest release! closing this issue now!
